In [1]:
!nvidia-smi

Fri May 24 00:32:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.80                 Driver Version: 546.80       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX350         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P0              N/A / ERR! |      0MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch 
print(torch.__version__)

2.1.1+cpu


### tensors
scalar

In [3]:
scalar =torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.ndim)
print(scalar.item())

0
7


In [5]:
vector = torch.tensor([7,7])
print(vector.ndim)

1


In [6]:
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[1,3,4] ,
                    [2,4,1] ])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 1]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
TENSOR = torch.tensor([[[3,4,1] 
                        , [5,1,2] 
                        ,[6,2,9] 
                        , [4,2,1]] , [[2,5,1] , [3,1,2] , [6,3,8] , [4,1,2]] ])
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([2, 4, 3])

In [13]:
random_tensor = torch.rand(3 , 3 , 4)
random_tensor
print(random_tensor.ndim)

3


In [14]:
random_tensor

tensor([[[0.4135, 0.3077, 0.3243, 0.2032],
         [0.2449, 0.7298, 0.1232, 0.4298],
         [0.8571, 0.7468, 0.6756, 0.9337]],

        [[0.6659, 0.8425, 0.9123, 0.9795],
         [0.2859, 0.6256, 0.7691, 0.3082],
         [0.2821, 0.1629, 0.3100, 0.9048]],

        [[0.1169, 0.1392, 0.7299, 0.3448],
         [0.1093, 0.2415, 0.7070, 0.9798],
         [0.1792, 0.2851, 0.7453, 0.0295]]])

In [15]:
#image like tensor 
random_image_tensor = torch.rand(size = (224 , 224 , 3))
# heigh , width , color channels (red , gree , blue)
random_image_tensor

tensor([[[0.2660, 0.5735, 0.7287],
         [0.9336, 0.2463, 0.5659],
         [0.0252, 0.5677, 0.3582],
         ...,
         [0.3148, 0.4219, 0.6867],
         [0.1595, 0.7640, 0.2185],
         [0.6576, 0.2412, 0.8630]],

        [[0.0313, 0.9498, 0.8272],
         [0.3469, 0.0353, 0.0565],
         [0.7066, 0.7446, 0.6985],
         ...,
         [0.2697, 0.6986, 0.1605],
         [0.0701, 0.3697, 0.1765],
         [0.1228, 0.3981, 0.2696]],

        [[0.6322, 0.6118, 0.2369],
         [0.0484, 0.6757, 0.0052],
         [0.3029, 0.9185, 0.4175],
         ...,
         [0.9722, 0.9692, 0.1896],
         [0.1246, 0.5698, 0.7356],
         [0.4276, 0.2200, 0.8667]],

        ...,

        [[0.1566, 0.2687, 0.1103],
         [0.0861, 0.9304, 0.4783],
         [0.5853, 0.7766, 0.4022],
         ...,
         [0.2669, 0.7724, 0.6924],
         [0.7785, 0.2037, 0.2201],
         [0.4536, 0.5131, 0.4817]],

        [[0.6432, 0.6288, 0.6549],
         [0.4418, 0.0217, 0.3749],
         [0.

In [16]:
torch.rand(224 , 224 , 3)

tensor([[[0.3208, 0.1322, 0.1895],
         [0.8922, 0.5363, 0.4126],
         [0.6388, 0.0102, 0.8557],
         ...,
         [0.4008, 0.6707, 0.9494],
         [0.8842, 0.7324, 0.6910],
         [0.2659, 0.3325, 0.6214]],

        [[0.5121, 0.5911, 0.2033],
         [0.8268, 0.3806, 0.4128],
         [0.9279, 0.8040, 0.2582],
         ...,
         [0.9683, 0.8741, 0.7266],
         [0.2913, 0.8424, 0.2745],
         [0.6063, 0.6076, 0.2739]],

        [[0.8884, 0.2162, 0.8664],
         [0.2103, 0.8498, 0.9791],
         [0.2802, 0.4099, 0.3120],
         ...,
         [0.4323, 0.8255, 0.7714],
         [0.9896, 0.5123, 0.9184],
         [0.4309, 0.4587, 0.0834]],

        ...,

        [[0.6134, 0.3329, 0.3563],
         [0.8590, 0.5869, 0.5498],
         [0.3837, 0.3868, 0.7797],
         ...,
         [0.0535, 0.0781, 0.7336],
         [0.1519, 0.0405, 0.3871],
         [0.0818, 0.8578, 0.5419]],

        [[0.1700, 0.2115, 0.9881],
         [0.0235, 0.1624, 0.7921],
         [0.

In [17]:
# zeroes and ones 
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(3 ,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
zeros.size()

torch.Size([3, 4])

In [20]:
random_image_tensor.size()

torch.Size([224, 224, 3])

In [21]:
#create a range of tensors and tensors like 
torchlike = torch.arange(start=10 , end=4000 , step=345)
torchlike.size()

torch.Size([12])

In [22]:
#creating a tensor like 
ten_zeroes = torch.zeros_like(input=torchlike)
ten_zeroes.size()

torch.Size([12])

In [23]:
#dealing with tensor data types 
#deafult data type of a tensor in pytorch is float32 , even if it is set to none 
float32_tensor = torch.tensor([2.0 , 3.0] , dtype=None)
float32_tensor.dtype

torch.float32

In [24]:
float32_tensor = torch.tensor([2.99999 , 3.7] , dtype=None #what type of datatype is your tensor 
                            , device=None ,  #what type of device is your tensor on ? 
                            requires_grad=False) # whether to track gradient or not with this tensor operations 
float32_tensor.dtype
print(float32_tensor)

tensor([3.0000, 3.7000])


1. tensors not being right datatype 
2. tensors not being right shape 
3. tensors not being right device 

**above are the top 3 errors occuring in the pytorch**

device me daalna hai cpu ya fir cuda (for using gpu )
device = "cuda"

for correcting the baove 3 errors we can use 
1. ```tensor.dtype```
2. `tensor.shape`
3. `tensor.device`

In [25]:
float_16_tensor = torch.tensor([3.2 , 5.7] , dtype=torch.float16)
float_16_tensor.dtype

torch.float16

## PERFORMING TENSOR OPERATIONS 
### MANIPULATING TENSORS 

In [26]:
tensor = torch.tensor([1 , 2 , 3])
tensor+10

tensor([11, 12, 13])

In [27]:
tensor*2

tensor([2, 4, 6])

In [28]:
tensor/3

tensor([0.3333, 0.6667, 1.0000])

In [29]:
torch.multiply(tensor , 10)

tensor([10, 20, 30])

In [30]:
torch.add(tensor , 2)

tensor([3, 4, 5])

In [31]:
torch.subtract(tensor , 3)

tensor([-2, -1,  0])

In [32]:
tensor*tensor

tensor([1, 4, 9])

In [33]:
torch.matmul(tensor , tensor)

tensor(14)

In [34]:
%%time
value = 0 
for i in range (len(tensor)):
    value+=tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.51 ms


tensor(14)

In [35]:
%%time 
for i in range(1 , 100000000):
    count=0

CPU times: total: 3.11 s
Wall time: 7.65 s


## MATRIX MULTIPLICATION 
multiplication of `(3 ,2 ) and (3 ,2)` wont work 
but `(2 , 3) and (3 ,2 )` will work

In [36]:
torch.matmul(torch.rand(2 , 3) , torch.rand(3 ,2))

tensor([[1.2206, 0.7826],
        [0.8905, 0.6405]])

In [37]:
torch.matmul(torch.rand(2 , 3) , torch.rand(3 ,9))

tensor([[0.2469, 0.9106, 0.9098, 1.0170, 0.7384, 0.3612, 0.2405, 0.7400, 0.9365],
        [0.2712, 1.0768, 1.1827, 1.2505, 1.0257, 0.4671, 0.3232, 0.8469, 1.1815]])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
two_tensor = torch.rand(2 ,3)
two_tensor

tensor([[0.6912, 0.1138, 0.1635],
        [0.9190, 0.5295, 0.7809]])

In [40]:
two_tensor.T

tensor([[0.6912, 0.9190],
        [0.1138, 0.5295],
        [0.1635, 0.7809]])

In [41]:
torch.mm(two_tensor.T , two_tensor)

tensor([[1.3224, 0.5653, 0.8307],
        [0.5653, 0.2933, 0.4321],
        [0.8307, 0.4321, 0.6366]])

In [42]:
torch.mm(two_tensor , two_tensor.T)

tensor([[0.5174, 0.8232],
        [0.8232, 1.7349]])

## FINDING THE MIN MAX , MEAN , (TENSOR AGGREGATION)


In [43]:
x = torch.arange(0 , 100 , 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.min(x)

tensor(0)

In [45]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [46]:
x.dtype

torch.int64

In [47]:
x = x.type(torch.float32)

In [48]:
x.mean()

tensor(45.)

In [49]:
torch.mean(x)

tensor(45.)

In [50]:
torch.sum(x) , x.sum()

(tensor(450.), tensor(450.))

In [51]:
random_tensur = torch.rand(10)

In [52]:
random_tensur

tensor([0.0901, 0.2541, 0.5483, 0.7063, 0.0920, 0.9156, 0.4396, 0.1018, 0.9325,
        0.0820])

### arg min and arg max gives the position where the min and max elements are there 

In [53]:
random_tensur.argmin()

tensor(9)

In [54]:
random_tensur.argmax()

tensor(8)

## reshaping , stacking , squeezing and unsqueezing the tensors 
* Reshaping - reshapes the input tensor to a defined shape 
* view - return a view of the input tensor of the certain shape but keep the same memory as the original tensor 
* stacking - to combine multiple tensors on the top of each other (vstack) , or side by side (hstack)
* squeeze - removes all `1` dimensions from the tensor 
* unsqueeze - adds a `1` dimenison to our target tensor 
* permute - return a view of the input with dimensions permuted(swapped) in a certain way 

In [55]:
import torch 
x = torch.arange(1. , 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
x.shape

torch.Size([9])

In [59]:
x_reshape = x.reshape(3 ,3)
x_reshape , x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [60]:
x_reshape = x.reshape(9,1)
x_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [61]:
# changing the view 
x = torch.arange(1. , 11. )
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [62]:
z = x.view(2 , 5)
z.shape

torch.Size([2, 5])

In [63]:
# changing z also changes x , as view shares the same memory as that of the original tensor 
z[0]=5
z , x

(tensor([[ 5.,  5.,  5.,  5.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.]))

In [64]:
z[0][2]=10
z , x

(tensor([[ 5.,  5., 10.,  5.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  5., 10.,  5.,  5.,  6.,  7.,  8.,  9., 10.]))

In [65]:
x=torch.arange(0,11)

In [66]:
x.shape

torch.Size([11])

In [67]:
x_stack = torch.stack([x ,x-10 ,x+10 ,x*10] , dim=-1)

In [68]:
x_stack

tensor([[  0, -10,  10,   0],
        [  1,  -9,  11,  10],
        [  2,  -8,  12,  20],
        [  3,  -7,  13,  30],
        [  4,  -6,  14,  40],
        [  5,  -5,  15,  50],
        [  6,  -4,  16,  60],
        [  7,  -3,  17,  70],
        [  8,  -2,  18,  80],
        [  9,  -1,  19,  90],
        [ 10,   0,  20, 100]])

In [69]:
x_stack.shape

torch.Size([11, 4])

In [70]:
torch.squeeze(x_stack)

tensor([[  0, -10,  10,   0],
        [  1,  -9,  11,  10],
        [  2,  -8,  12,  20],
        [  3,  -7,  13,  30],
        [  4,  -6,  14,  40],
        [  5,  -5,  15,  50],
        [  6,  -4,  16,  60],
        [  7,  -3,  17,  70],
        [  8,  -2,  18,  80],
        [  9,  -1,  19,  90],
        [ 10,   0,  20, 100]])

In [71]:
x = torch.arange(1 , 10  ,2)

In [72]:
x

tensor([1, 3, 5, 7, 9])

In [73]:
torch.squeeze(x)

tensor([1, 3, 5, 7, 9])

In [74]:
x = torch.rand(3 , 1 , 4 , 2)

In [75]:
x

tensor([[[[0.2936, 0.6978],
          [0.6957, 0.3771],
          [0.1349, 0.1505],
          [0.2886, 0.3654]]],


        [[[0.5567, 0.9399],
          [0.6671, 0.2869],
          [0.1028, 0.8791],
          [0.9579, 0.0111]]],


        [[[0.3971, 0.6500],
          [0.2033, 0.0108],
          [0.2348, 0.5561],
          [0.5139, 0.1669]]]])

In [76]:
y =torch.squeeze(x)
y

tensor([[[0.2936, 0.6978],
         [0.6957, 0.3771],
         [0.1349, 0.1505],
         [0.2886, 0.3654]],

        [[0.5567, 0.9399],
         [0.6671, 0.2869],
         [0.1028, 0.8791],
         [0.9579, 0.0111]],

        [[0.3971, 0.6500],
         [0.2033, 0.0108],
         [0.2348, 0.5561],
         [0.5139, 0.1669]]])

In [77]:
y.shape , x.shape

(torch.Size([3, 4, 2]), torch.Size([3, 1, 4, 2]))

In [78]:
z = torch.unsqueeze(y , dim=0)
y.shape , z.shape

(torch.Size([3, 4, 2]), torch.Size([1, 3, 4, 2]))

In [79]:
x= torch.randn(2 , 4 , 6)

In [80]:
x

tensor([[[ 0.1501, -0.9257,  0.4472,  0.0762,  1.3603, -0.6448],
         [-0.2892,  1.2468, -0.8025, -0.0059,  1.2569, -0.5375],
         [-0.9147, -0.9411, -0.0542, -1.2989,  0.7379,  1.3956],
         [-0.2430, -0.2109,  0.2653, -0.3964,  0.0231, -0.2218]],

        [[ 0.5190,  0.7793,  0.2060, -0.3015, -1.0477,  1.0419],
         [-0.4675,  1.1372, -1.0509,  0.4959,  0.7904,  0.2100],
         [-0.9582, -1.0549,  0.6559, -0.0036, -1.7059,  1.1989],
         [ 1.2657,  0.7470,  0.8796, -0.1377, -0.1848, -0.2551]]])

In [81]:
x.shape, torch.permute(x , (2 ,0 ,1)).shape  #this shifts the axis of 0-> 2 , 1-> 0 , 2-> 1 

(torch.Size([2, 4, 6]), torch.Size([6, 2, 4]))

In [82]:
# if we change the value of any tensor of x , the permuted tensors value will be also be changed

### NUMPY AND PYTORCH ARE VERY SIMILAR TO EACH OTHER , AND ARE INTERCHANGEABLE 

In [83]:
import torch 
import numpy as np

np_array = np.arange(1. , 10. )

In [84]:
np_array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
tensor = torch.from_numpy(np_array).type(torch.float32)

In [86]:
tensor , tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [87]:
# the default data type of the numpy is float64 
# but that of a tensor is float32

In [88]:
tensor = torch.ones(1 ,6)
tensor

tensor([[1., 1., 1., 1., 1., 1.]])

In [89]:
np_tensor = tensor.numpy()
np_tensor

array([[1., 1., 1., 1., 1., 1.]], dtype=float32)

In [90]:
np_tensor.dtype

dtype('float32')

In [91]:
# to reduce the randomness in the neural network , there is a concept called **random seed**
# essentially what the random seed does is to add the flavourness in the randomness 


In [92]:
import torch 

# create two random tensors 
random_tensor_a = torch.rand(3 ,4)
random_tensor_b = torch.rand(3 ,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.1853, 0.6086, 0.0630, 0.6411],
        [0.7530, 0.2918, 0.3930, 0.1672],
        [0.9506, 0.0166, 0.7483, 0.7919]])
tensor([[0.8911, 0.2740, 0.2456, 0.5234],
        [0.8151, 0.4159, 0.6732, 0.6863],
        [0.9394, 0.9233, 0.2301, 0.8493]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [93]:
# now lets make some random but reproducable tensors 
import torch 
# set the random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3 ,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3 ,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [94]:
# runnign pytorch and tensors on the gpu ( to make the faster computations )

# gpu is for faster computations of the numbers 
!nvidia-smi

Fri May 24 00:35:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.80                 Driver Version: 546.80       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX350         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0              N/A / ERR! |      0MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [95]:
torch.cuda.is_available()

False

In [96]:
import torch
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
else:
    print("No GPU available. Training will run on CPU.")


No GPU available. Training will run on CPU.


In [97]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [98]:
torch.cuda.device_count()

0

In [99]:
!nvidia-smi

Fri May 24 00:35:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.80                 Driver Version: 546.80       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX350         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0              N/A / ERR! |      0MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--